name: build-jiji-debug

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build-debug:
    runs-on: windows-2019

    env:
      BOOST_ROOT: ${{github.workspace}}/3rdparty/boost
      BOOST_URL: https://sourceforge.net/projects/boost/files/boost/1.76.0/boost_1_76_0.tar.bz2/download

    steps:
    - name: check out
      uses: actions/checkout@v2

    - name: check out third parties
      uses: actions/checkout@v2
      with:
        repository: gleb-cherkayev/lili-third-party
        path: third-party
        ref: jiji
        token: ${{ secrets.REPO_ACCESS_TOKEN }}

    - name: Restore Boost cache
      uses: actions/cache@v2
      id: cache-boost
      with:
        path: ${{env.BOOST_ROOT}}
        key: boost

    - name: Install Boost
      if: steps.cache-boost.outputs.cache-hit != 'true'
      run: |
        if [ "$OS" == "Windows_NT" ]; then
          # fix up paths to be forward slashes consistently
          BOOST_ROOT=$(echo $BOOST_ROOT | sed 's/\\/\//g')
        fi
        mkdir -p $BOOST_ROOT
        curl --progress-bar --location --output $BOOST_ROOT/download.tar.bz2 $BOOST_URL
        7z -o$BOOST_ROOT x $BOOST_ROOT/download.tar.bz2 -y -bd
        7z -o$BOOST_ROOT x $BOOST_ROOT/download.tar -y -bd
        cd $BOOST_ROOT && cp -r boost_*/* .
        rm -rf boost_*/* download.tar.bz2 download.tar
      shell: bash

    - name: (jiji-all) generate solution
      run: ./generate_msvc2019.bat
      working-directory: .

    - name: (jiji-all) build (debug)
      run: ./build_debug.bat
      working-directory: .
